# Generated by Django 4.0.2 on 2022-10-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrappuccinoParadise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Drink',
        ),
    ]
