# Generated by Django 4.0.2 on 2022-10-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrappuccinoParadise', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='canMake',
        ),
    ]
