# Generated by Django 4.0.2 on 2022-10-24 00:01

from django.db import migrations


def populate_ingredients_and_drinks(apps, schema_editor):
    Ingredient = apps.get_model('FrappuccinoParadise', 'Ingredient')
    Drink = apps.get_model('FrappuccinoParadise', 'Drink')

    coffee_beans = Ingredient.objects.create(name="Coffee Beans", cost=1)
    milk = Ingredient.objects.create(name="Milk", cost=1)
    cinnamon = Ingredient.objects.create(name="Cinnamon", cost=0.50)
    ice_cream = Ingredient.objects.create(name="Ice Cream", cost=2)
    egg = Ingredient.objects.create(name="Egg", cost=1)
    sugar = Ingredient.objects.create(name="Sugar", cost=0.25)
    creamer = Ingredient.objects.create(name="Creamer", cost=0.50)
    matcha = Ingredient.objects.create(name="Matcha", cost=1)
    vanilla = Ingredient.objects.create(name="Vanilla", cost=1)
    honey = Ingredient.objects.create(name="Honey", cost=1)

    coffee_beans.save()
    milk.save()
    cinnamon.save()
    ice_cream.save()
    egg.save()
    sugar.save()
    creamer.save()
    matcha.save()
    vanilla.save()
    honey.save()

    black_coffee = Drink.objects.create(name="Black Coffee", cost=2)
    black_coffee.ingredients.add(coffee_beans)

    espresso = Drink.objects.create(name="Espresso", cost=4)
    espresso.ingredients.add(coffee_beans, milk)

    egg_coffee = Drink.objects.create(name="Egg Coffee", cost=6)
    egg_coffee.ingredients.add(coffee_beans, milk, egg)

    coffee_float = Drink.objects.create(name="Coffee Float", cost=6)
    coffee_float.ingredients.add(coffee_beans, ice_cream)

    matcha_coffee = Drink.objects.create(name="Matcha Coffee", cost=4)
    matcha_coffee.ingredients.add(coffee_beans, matcha)

    sugar_and_honey = Drink.objects.create(name="Sugar and Honey", cost=3)
    sugar_and_honey.ingredients.add(coffee_beans, sugar, honey)

    black_coffee.save()
    espresso.save()
    egg_coffee.save()
    coffee_float.save()
    matcha_coffee.save()
    sugar_and_honey.save()


class Migration(migrations.Migration):

    dependencies = [
        ('FrappuccinoParadise', '0010_give_users_names'),
    ]

    operations = [
        migrations.RunPython(populate_ingredients_and_drinks),
    ]
