# Generated by Django 4.0.2 on 2022-10-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrappuccinoParadise', '0012_remove_order_isactive_order_isdelivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.drink')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.order')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.ingredient')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.drink')),
            ],
        ),
    ]
