# Generated by Django 4.0.2 on 2022-10-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrappuccinoParadise', '0014_restore_drink_ingredient_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.ingredient')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrappuccinoParadise.orderitem')),
            ],
        ),
    ]
