# Generated by Django 4.0.2 on 2022-11-09 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrappuccinoParadise', '0015_rename_ingredient_ingredientitem_ingredient_addon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerName',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
